name: Branch Info Workflow

on:
  push:
    branches:
      - dev
      - staging

jobs:
  display-branch-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display branch information
        run: |
          echo "Este workflow está rodando na branch: ${{ github.ref }}"
          echo "Nome curto da branch: ${{ github.ref_name }}"
