name: CI Workflow

on:
  push:
    branches:
      - dev
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display branch name
        run: echo "This workflow is running on branch: ${{ github.ref }}"
