# workflow.yml
name: Build and Push to ECR

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: nginx-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build and Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Create Dockerfile
          echo "FROM nginx:alpine" > Dockerfile
          echo "COPY index.html /usr/share/nginx/html/" >> Dockerfile
          echo "EXPOSE 80" >> Dockerfile

          # Create index.html
          echo "<!DOCTYPE html>" > index.html
          echo "<html><head><title>Nginx Docker</title></head>" >> index.html
          echo "<body><h1>Hello from Nginx!</h1></body></html>" >> index.html

          # Build and push
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
