name: Deploy EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Launch EC2 instance
      run: |
        aws ec2 run-instances --image-id ami-0866a3c8686eaeeba --instance-type t2.micro --key-name GIT --security-group-ids sg-073358f05d6d35f4b --subnet-id subnet-00535fc3008d42be5 --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MyInstance}]'
