name: Deploy EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Launch EC2 instance
    run: |
    # Variables
    INSTANCE_TYPE="t2.micro"  # Change this to your desired instance type
    AMI_ID="ami-0866a3c8686eaeeba"  # Replace with your desired AMI ID
    KEY_NAME="GIT"  # Replace with your key pair name
    SECURITY_GROUP="sg-073358f05d6d35f4b"  # Replace with your security group ID
    SUBNET_ID="subnet-073358f05d6d35f4b"  # Replace with your subnet ID

    # Launch the EC2 instance
    INSTANCE_ID=$(aws ec2 run-instances \
      --image-id $AMI_ID \
      --count 1 \
      --instance-type $INSTANCE_TYPE \
      --key-name $KEY_NAME \
      --security-group-ids $SECURITY_GROUP \
      --subnet-id $SUBNET_ID \
      --query "Instances[0].InstanceId" \
      --output text)

    echo "Launched EC2 instance with ID: $INSTANCE_ID"

    # Optionally, you can add a wait command to ensure the instance is running
    aws ec2 wait instance-running --instance-ids $INSTANCE_ID

    echo "EC2 instance is now running."
