name: Check Odd or Even

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Enter a number to check if it is odd or even'
        required: true
        default: '0'

jobs:
  check-odd-even:
    runs-on: ubuntu-latest
    steps:
      - name: Display input number
        run: |
          echo "You entered the number: ${{ github.event.inputs.number }}"
          
          if (( ${{ github.event.inputs.number }} % 2 == 0 )); then
            echo "The number ${{ github.event.inputs.number }} is even."
          else
            echo "The number ${{ github.event.inputs.number }} is odd."
          fi
